# Sourced from https://github.com/zerforschung/schnelltesttest.de
name: Deploy to Production

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  repository_dispatch:
    types:
      - redeploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
    name: Production
      url: https://vegancheck.me

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'yarn'

      - run: yarn install
      - run: yarn build

      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2
        env:
          ARGS: '-rltgoDzvO --delete'
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY_PRIVATE }}
          REMOTE_HOST: ${{ secrets.UBERSPACE_HOST }}
          REMOTE_USER: ${{ secrets.UBERSPACE_USER }}
          TARGET: vegancheck.me/
