name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://vegancheck.me
    retries: 3 # Number of times to retry the job
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.UBERSPACE_HOST }}
        username: ${{ secrets.UBERSPACE_USER }}
        key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
        port: 22
        script_stop: true
        script: |
          cd vegancheck.me
          git reset --hard HEAD
          git clean -f -d
          git pull
          npm i next
          npm run build
          supervisorctl restart vegancheck
