name: Production Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://vegancheck.me
    steps:
    - name: executing remote ssh commands using password
      id: ssh
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.UBERSPACE_HOST }}
        username: ${{ secrets.UBERSPACE_USER }}
        key: ${{ secrets.DEPLOY_KEY_PRIVATE }}
        port: 22
        script_stop: true
        script: |
          cd vegancheck.me
          git reset --hard HEAD
          git clean -f -d
          git pull
          npm i next
          npm run build
          supervisorctl restart vegancheck
    - name: Check for failure
      run: exit ${{ steps.ssh.outcome }}
      shell: bash
    - name: Retry on failure
      if: failure()
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        registry-url: 'https://registry.npmjs.org'
      run: |
        npm install @actions/core @actions/exec @actions/retry
        node -e "const {retry} = require('@actions/retry'); retry(async () => { throw new Error('Something went wrong'); }, { retries: 3, minTimeout: 10000, maxTimeout: 30000, onRetry: error => core.warning(`Retry failed with error: \${error}`) })"
