name: E2E Tests

on:
  push:
    branches: [staging, main]
  repository_dispatch:
    types:
      - redeploy
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - run: npm install
      - run: npm run dev
      - run: npm run test
